# Generated by Django 5.2.4 on 2025-07-06 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='titel',
            new_name='title',
        ),
    ]
