# Generated by Django 5.2.4 on 2025-07-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_rename_titel_note_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
